### ISSUE TITLE
ArgumentError: Unknown api version when using getEnrollmentGroupAttestationMechanism

### ISSUE THREAD

**Issue by lhpluke** [Azure/azure-iot-dps-node#9]
Hello! Whenever I try to get my enrollment group attestation mechanism I get this error:

```
D:\company\company-backend\node_modules\azure-iot-http-base\dist\rest_api_client.js:261
                error = new azure_iot_common_1.errors.ArgumentError(message);
                        ^
ArgumentError: Unknown api version
    at Function.translateError (D:\company\company-backend\node_modules\azure-iot-http-base\dist\rest_api_client.js:261:25)
    at requestCallback (D:\company\company-backend\node_modules\azure-iot-http-base\dist\rest_api_client.js:183:40)
    at IncomingMessage.<anonymous> (D:\company\company-backend\node_modules\azure-iot-http-base\dist\http.js:117:17)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

This is my code:
(I have a breakpoint so I can see the output before it returns null)
```
async getCustomerDPSGroups(): Promise<QueryResult> {
        try {
            
            var serviceClient = ProvisioningServiceClient.fromConnectionString(process.env.AZURE_IOT_SERVICE_KEY)

            var returnedInformation = await new Promise((resolve, reject) => {
                serviceClient.getEnrollmentGroupAttestationMechanism("company-enrollment-group")
            })
            console.log("RETURNED DATA: ", returnedInformation)

            return null;

        }
        catch (error) {
            throw new UnprocessableEntityException(error);
        }
}
```

Thank you!

**Comment by lhpluke** [comment]
It turns out I was using the wrong symmetric key to access the DPS. The error is gone now that I'm using the right one. Sorry!
